### ISSUE TITLE
如果打的debug包，没有去掉unity自带的development console，

### ISSUE THREAD

**Issue by ThisIsUniqueName** [hiramtan/HiDebug_unity#3]
如果打的debug包，没有去掉unity自带的异常日志窗口development console，
若未使用hilog，使用Debug.developerConsoleVisible = false;则可以去掉development coonsole.
使用了hilog后  development coonsole去不掉

**Comment by hiram3512** [comment]
插件使用旧版unity开发,那时没有development console窗口(已不做unity开发,也不知道这个窗口什么功能),建议:HiLog监听的Application的日志回调事件,调试看一下设置HiLog开启时是否同时影响了unity自带的窗口设置(或者监听的事件是否仍旧被自带的窗口监听)
